name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: kalilinux/kali-rolling
								ssh_key: ${{ secrets.SSH_KEY }}
								key_file: id_ecdsa
                  run: |
                 apt update && apt -y install kali-linux-large
               
